/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#005762",
        "surface-container-low": "#091328",
        "error-container": "#9f0519",
        "primary-fixed-dim": "#00d4ec",
        "on-tertiary": "#290067",
        "on-secondary-fixed": "#064200",
        "error": "#ff716c",
        "tertiary-dim": "#874cff",
        "primary-container": "#00e3fd",
        "primary": "#81ecff",
        "error-dim": "#d7383b",
        "on-error": "#490006",
        "surface-container-lowest": "#000000",
        "on-secondary": "#0b5800",
        "inverse-on-surface": "#4d556b",
        "tertiary-container": "#7000ff",
        "secondary-container": "#106e00",
        "on-tertiary-fixed": "#1f0052",
        "tertiary": "#ac89ff",
        "tertiary-fixed": "#bda1ff",
        "on-primary-fixed": "#003840",
        "on-surface-variant": "#a3aac4",
        "tertiary-fixed-dim": "#b190ff",
        "surface-container-highest": "#192540",
        "secondary-fixed-dim": "#2be800",
        "surface-container": "#0f1930",
        "on-error-container": "#ffa8a3",
        "outline": "#6d758c",
        "on-tertiary-container": "#f8f1ff",
        "secondary": "#2ff801",
        "surface-dim": "#060e20",
        "surface-variant": "#192540",
        "surface-container-high": "#141f38",
        "surface-bright": "#1f2b49",
        "on-secondary-fixed-variant": "#0d6200",
        "on-primary-fixed-variant": "#005762",
        "on-secondary-container": "#e7ffd9",
        "on-surface": "#dee5ff",
        "secondary-fixed": "#2ff801",
        "inverse-primary": "#006976",
        "on-primary-container": "#004d57",
        "primary-fixed": "#00e3fd",
        "on-background": "#dee5ff",
        "surface": "#060e20",
        "secondary-dim": "#2be800",
        "background": "#060e20",
        "inverse-surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#4700a7",
        "surface-tint": "#81ecff",
        "primary-dim": "#00d4ec",
        "outline-variant": "#40485d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}

